version: '3.4'

services:
  ginfast:
    image: ginfast:v1
    privileged: true
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./app/logs:/app/logs
      - ./app/conf:/app/conf
    ports:
      - "7890:7890"

